import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";

//所有頁面、所有 component，都一定會被包在這個檔案裡

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {//類似HTML <head> 的內容
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {//children = 目前顯示的頁面
  return (
    <html lang="zh-Hant">
      <body style={{ background: '#fff' }}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
//Providers 不負責畫畫面 專門「包住全站」
//被 Providers 包住的元件，都能用 useAuth() 拿到狀態